[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "fluxpype"
version = "0.1.2"
description = "A basic Python project"
readme = "README.md"
requires-python = ">=3.8"

[project.urls]
Homepage = "https://github.com/gillyspace27/fluxpype"

# [tool.setuptools]
# packages = { find = { where = ["src/"] } }

# [project.dependencies]
# dependencies = [
#     "matplotlib",
#     "sunpy"
# ]
