[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "fluxpype"
version = "0.1.4"
description = "A wrapper and installer for the FLUX Model"
readme = "README.md"
requires-python = ">=3.8"
license = { file = "LICENSE" }

classifiers = ["Programming Language :: Python :: 3.8"]

dependencies = [
    "matplotlib",
    "sunpy",
    "pandas",
    "tqdm",
    "astropy",
    "bs4",
    "lxml",
    "zeep",
    "drms",
    "timeout_decorator",
]

[project.optional-dependencies]
FLUXcore = []

[project.urls]
Homepage = "https://github.com/gillyspace27/fluxpype"
BaseProject = "https://github.com/lowderchris/fluxon-mhd"
